MVCproyecto/Models/ClienteProducto.cs
using System.ComponentModel.DataAnnotations;

namespace MVCproyecto.Models
{
    public class Cliente
    {
        public int Id { get; set; }
        [StringLength(11)]
        public string? cedula { get; set; }
        [StringLength(75)]
        public string? nombre { get; set; }
        [StringLength(75)]
        public string? apellido { get; set; }
        public int edad { get; set; }
        [StringLength(75)]
        public string? correo { get; set; }
    }

    public class Producto
    {
        public int Id { get; set; }
        [StringLength(75)]
        public string? codigo { get; set; }
        [StringLength(75)]
        public string? nombre { get; set; }
        [StringLength(75)]
        public string? descripcion { get; set; }
        public double valor { get; set; }
        public int cantidad { get; set; }
    }
}

MVCproyecto/Models/ErrorViewModel.cs
namespace MVCproyecto.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCproyecto/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using MVCproyecto.Models;

namespace MVCproyecto.Controllers
{
    public class ClienteController : Controller
    {

        private readonly APIGateway _api;

        public ClienteController(APIGateway api)
        {
            this._api = api;
        }
        //Crear una lista de lo que ve
        public IActionResult Index()
        {
            List<Cliente> clientes;
            clientes = _api.ListCliente();
            return View(clientes);
        }

        [HttpGet]
        public IActionResult Create() {
            Cliente cliente = new Cliente();
            return View(cliente);
        }

        [HttpPost]
        public IActionResult Create(Cliente cliente)
        {
            _api.CrearCliente(cliente);
            return RedirectToAction("Index");
        }

        public IActionResult Details (int id)
        {
            Cliente cliente;

            //obtener cliente de la api
            cliente = _api.GetCliente(id);
            return View(cliente);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Cliente cliente;
            cliente = _api.GetCliente(id);
            return View(cliente);
        }

        [HttpPost]
        public IActionResult Edit(Cliente cliente)
        {
            _api.ActualizarCliente(cliente);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Cliente cliente;
            cliente = _api.GetCliente(id);
            return View(cliente);
        }

        [HttpPost]
        public IActionResult Delete(Cliente cliente)
        {
            _api.EliminarCliente(cliente.Id);
            return RedirectToAction("Index");
        }
    }
}

MVCproyecto/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCproyecto.Models;
using System.Diagnostics;

namespace MVCproyecto.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCproyecto/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using MVCproyecto.Models;

namespace MVCproyecto.Controllers
{
    public class ProductoController : Controller
    {
        private readonly APIGateway _api;

        public ProductoController(APIGateway api)
        {
            this._api = api;
        }
        //Crear una lista de lo que ve
        public IActionResult Index()
        {
            List<Producto> producto;
            producto = _api.ListProducto();
            return View(producto);
        }

        [HttpGet]
        public IActionResult Create()
        {
            Producto producto = new Producto();
            return View(producto);
        }

        [HttpPost]
        public IActionResult Create(Producto producto)
        {
            _api.CrearProducto(producto);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Producto producto;
            //obtener el producto de la api
            producto = _api.GetProducto(id);

            return View(producto);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Producto producto;
            producto = _api.GetProducto(id);
            return View(producto);
        }

        [HttpPost]
        public IActionResult Edit(Producto producto)
        {
            _api.ActualizarProducto(producto);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Producto producto;
            producto = _api.GetProducto(id);
            return View(producto);
        }

        [HttpPost]
        public IActionResult Delete(Producto producto)
        {
            _api.EliminarProducto(producto.Id);
            return RedirectToAction("Index");
        }
    }
}

MVCproyecto/Views/Cliente/Create.cshtml
@model MVCproyecto.Models.Cliente

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="cedula" class="control-label"></label>
                <input asp-for="cedula" class="form-control" />
                <span asp-validation-for="cedula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="apellido" class="control-label"></label>
                <input asp-for="apellido" class="form-control" />
                <span asp-validation-for="apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="edad" class="control-label"></label>
                <input asp-for="edad" class="form-control" />
                <span asp-validation-for="edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="correo" class="control-label"></label>
                <input asp-for="correo" class="form-control" />
                <span asp-validation-for="correo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCproyecto/Views/Cliente/Delete.cshtml
@model MVCproyecto.Models.Cliente

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cedula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cedula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.edad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.correo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-info" asp-action="Index">Back to List</a>
    </form>
</div>

MVCproyecto/Views/Cliente/Details.cshtml
@model MVCproyecto.Models.Cliente

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cedula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cedula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.edad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.correo)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }, 
    new { onclick = "return confirmation();", @class = "btn btn-primary"}) |
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

MVCproyecto/Views/Cliente/Edit.cshtml
@model MVCproyecto.Models.Cliente

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cedula" class="control-label"></label>
                <input asp-for="cedula" class="form-control" />
                <span asp-validation-for="cedula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="apellido" class="control-label"></label>
                <input asp-for="apellido" class="form-control" />
                <span asp-validation-for="apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="edad" class="control-label"></label>
                <input asp-for="edad" class="form-control" />
                <span asp-validation-for="edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="correo" class="control-label"></label>
                <input asp-for="correo" class="form-control" />
                <span asp-validation-for="correo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCproyecto/Views/Cliente/Index.cshtml
@model IEnumerable<MVCproyecto.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}

<h1>Clientes</h1>
<style>
    h1 {
        color: white;
        font-family: 'Times New Roman', Times, serif;
    }
</style>

<p>
    <a class="btn btn-success" asp-action="Create">Crear nuevo cliente</a>
</p>
<table class="table table-dark">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cedula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.edad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.correo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cedula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.edad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.correo)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {id=item.Id }, 
                new { onclick = "return confirmation();", @class = "btn btn-primary"}) |
                @Html.ActionLink("Details", "Details", new { id=item.Id },
                new { onclick = "return confirmation();", @class = "btn btn-primary"}) |
                @Html.ActionLink("Delete", "Delete", new {id=item.Id },
                new { onclick = "return confirmation();", @class = "btn btn-danger"})
            </td>
        </tr>
}
    </tbody>
</table>

MVCproyecto/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <h1 class="display-4">Welcome To Petshop</h1>
    <style>
        h1{
            color: white;
        }

        .slider{
            width: 100%;
            height: 100%;
            overflow: hidden;

        }

        .slider ul{
			display: flex;
			animation: cambio 20s infinite alternate linear;
            width: 400%;
        }

        .slider li{
            width: 100%;
            list-style: none;
        }

        .slider img{
			width: 100%;
			height: 100%;
		}
    </style>

    <div class="slider">
        <ul>
            <img src="https://images.hola.com/imagenes/mascotas/20220325206925/perros-significado-juguetes-favoritos-dn/1-67-423/que-significan-juguetes-para-mi-perro-t.jpg" alt=""></li>
            <li><img src="https://soyunperro.com/wp-content/uploads/2017/09/perro-cpm-juguetes.jpg" alt=""></li>
            <li><img src="https://animalnatura.com/img/leoblog/b/1/92/lg-b-juguetes%20para%20perros.jpg" alt=""></li>
            <li><img src="https://m.media-amazon.com/images/I/41b0QuHR7lL.jpg" alt=""></li>
            <li><img src="https://www.consumer.es/wp-content/uploads/2019/07/img_perros-juguetes-favoritos-2-art.jpg" alt=""></li>
		</ul>
    </div>
</div>

MVCproyecto/Views/Producto/Create.cshtml
@model MVCproyecto.Models.Producto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Producto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="codigo" class="control-label"></label>
                <input asp-for="codigo" class="form-control" />
                <span asp-validation-for="codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="descripcion" class="control-label"></label>
                <input asp-for="descripcion" class="form-control" />
                <span asp-validation-for="descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="valor" class="control-label"></label>
                <input asp-for="valor" class="form-control" />
                <span asp-validation-for="valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cantidad" class="control-label"></label>
                <input asp-for="cantidad" class="form-control" />
                <span asp-validation-for="cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCproyecto/Views/Producto/Delete.cshtml
@model MVCproyecto.Models.Producto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Producto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.valor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.valor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cantidad)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-info" asp-action="Index">Back to List</a>
    </form>
</div>

MVCproyecto/Views/Producto/Details.cshtml
@model MVCproyecto.Models.Producto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.valor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.valor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cantidad)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }, 
    new { onclick = "return confirmation();", @class = "btn btn-primary"}) |
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

MVCproyecto/Views/Producto/Edit.cshtml
@model MVCproyecto.Models.Producto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Producto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="codigo" class="control-label"></label>
                <input asp-for="codigo" class="form-control" />
                <span asp-validation-for="codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="descripcion" class="control-label"></label>
                <input asp-for="descripcion" class="form-control" />
                <span asp-validation-for="descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="valor" class="control-label"></label>
                <input asp-for="valor" class="form-control" />
                <span asp-validation-for="valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cantidad" class="control-label"></label>
                <input asp-for="cantidad" class="form-control" />
                <span asp-validation-for="cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCproyecto/Views/Producto/Index.cshtml
@model IEnumerable<MVCproyecto.Models.Producto>

@{
    ViewData["Title"] = "Index";
}

<h1>Productos</h1>
<style>
    h1{
        color: white;
        font-family: 'Times New Roman', Times, serif;
    }
</style>

<p>
    <a class="btn btn-success" asp-action="Create">Crear un producto</a>
</p>
<table class="table table-dark">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.codigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cantidad)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.valor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cantidad)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id },
                new { onclick = "return confirmation();", @class = "btn btn-primary"}) |
                @Html.ActionLink("Details", "Details", new { id=item.Id },
                new { onclick = "return confirmation();", @class = "btn btn-primary"}) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id },
                new { onclick = "return confirmation();", @class = "btn btn-danger"})
            </td>
        </tr>
}
    </tbody>
</table>

MVCproyecto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCproyecto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCproyecto.styles.css" asp-append-version="true" />
    <style>
        body {
            background: #3a6186; /* fallback for old browsers */
            background: -webkit-linear-gradient(to right, #89253e, #3a6186); /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to right, #89253e, #3a6186); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        }

        div{
            color: white;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://static.vecteezy.com/system/resources/thumbnails/005/601/776/small/pet-shop-logo-vector.jpg" alt="Logo" width="40" height="40" class="d-inline-block align-text-top">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Index">Productos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVCproyecto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>